### PR TITLE
Report battery voltage for iBeacons

### PR DESCRIPTION
**Pull request by DigiH**
## Description:
Report battery voltage for iBeacons which transmit this information instead of the tx power.

Included test case.

## Checklist:
  - [x] The pull request is done against the latest development branch
  - [x] Only one feature/fix was added per PR and the code change compiles without warnings
  - [x] I accept the [DCO](https://github.com/theengs/decoder/blob/development/docs/participate/development.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by DigiH** [comment]
Closing, due to failing iBeacon test. 

@h2zero  Not exactly sure why the test is failing, as both tx power and battery reporting iBeacons work fine for me here locally.

**Comment by h2zero** [comment]
```
deserializeJson() failed: NoMemory
```
Failing in other platforms due to different memory profiles. You'll need to increase the buffer size.

**Comment by DigiH** [comment]
Reopening after m_docMax increase

**Comment by h2zero** [comment]
hold on, I think it's the buffer allocated in the test that is failing, not in the decoder.h

**Comment by DigiH** [comment]
> hold on, I think it's the buffer allocated in the test that is failing, not in the decoder.h

Sorry, stopping here now

But passed in the last test with 10240, was just trying to go down step by step again.

**Comment by h2zero** [comment]
I'll test it locally to be sure. just need a few minutes

**Comment by h2zero** [comment]
Ok, looks like it passed now lol. Locally it worked with only 5500 allocated, odd that it needs to be higher for the CI tests.

**Comment by DigiH** [comment]
> Ok, looks like it passed now lol. Locally it worked with only 5500 allocated, odd that it needs to be higher for the CI tests.

That's how I experienced it here. I'll better go down again to the lowest where the test still passes, but it's not as high as 10240 ;)

**Comment by h2zero** [comment]
I'll create a quick buffer peak test, clang was the highest I saw in the logs at 7086

**Comment by DigiH** [comment]
> I'll create a quick buffer peak test, clang was the highest I saw in the logs at 7086

Just came to the same result here, 6656 starts failing again ;)

7168 it is

**Comment by DigiH** [comment]
@h2zero Thanks a lot for your promt pointers and help with this!

**Comment by h2zero** [comment]
You're welcome

**Comment by 1technophile** [comment]
Thanks!

**Pull request merged**
