### PR TITLE
Add PROGMEM decorator to JSON strings.

### PR DESCRIPTION
**Pull request by h2zero**
## Description:
This is to reduce the RAM consumption on the esp8266/avr by reading the decoder data from flash instead of RAM.

## Checklist:
  - [X] The pull request is done against the latest development branch
  - [X] Only one feature/fix was added per PR and the code change compiles without warnings
  - [X] I accept the [DCO](https://github.com/theengs/decoder/blob/development/docs/participate/development.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by DigiH** [comment]
And all still running smoothly on the non-affected ESP32 builds on my test ESP32. 

Might be time to ask @thardie for a test drive ;)

**Comment by h2zero** [comment]
OMG build test passing: https://github.com/h2zero/OpenMQTTGateway/actions/runs/2837296816

**Comment by 1technophile** [comment]
let me try it with an HM10

**Comment by 1technophile** [comment]
Having also a crash with the PR, unfortunately. 
```
[env:nodemcuv2-test-ble]
platform = ${com.esp8266_platform}
board = nodemcuv2
lib_deps =
  ${com-esp.lib_deps}
  ;${libraries.wire}
  ${libraries.decoder}
  ${libraries.wifimanager8266}
build_flags = 
  ${com-esp.build_flags}
  '-DZgatewayBT="BT"'
  '-DTimeBtwRead=10000'
board_build.flash_mode = dout
```
```
Advanced Memory Usage is available via "PlatformIO Home > Project Inspect"
RAM:   [=====     ]  47.2% (used 38692 bytes from 81920 bytes)
Flash: [======    ]  61.4% (used 640868 bytes from 1044464 bytes)
```
```
Exception 3: LoadStoreError: Processor internal physical address or data error during load or store
PC: 0x40230580
EXCVADDR: 0x40285d95

Decoding stack results
```

I went back to v0.2.2 and it runs (not saying it works, but the ESP8266 doesn't crash)
I'm with this memory usage with v0.2.2:
```
Advanced Memory Usage is available via "PlatformIO Home > Project Inspect"
RAM:   [========  ]  84.2% (used 69008 bytes from 81920 bytes)
Flash: [======    ]  60.5% (used 631828 bytes from 1044464 bytes)
```

v0.4.0 -> no crash
```
Checking size .pio\build\nodemcuv2-test-ble\firmware.elf
Advanced Memory Usage is available via "PlatformIO Home > Project Inspect"
RAM:   [========  ]  84.7% (used 69412 bytes from 81920 bytes)
Flash: [======    ]  60.6% (used 632660 bytes from 1044464 bytes)
Building .pio\build\nodemcuv2-test-ble\firmware.bin
```

v0.5.0 -> crash
```
Checking size .pio\build\nodemcuv2-test-ble\firmware.elf
Advanced Memory Usage is available via "PlatformIO Home > Project Inspect"
RAM:   [========= ]  94.4% (used 77352 bytes from 81920 bytes)
Flash: [======    ]  61.3% (used 640768 bytes from 1044464 bytes)
Building .pio\build\nodemcuv2-test-ble\firmware.bin
```

```

Unhandled C++ exception: OOM

>>>stack>>>
```

I'm asking myself if this is not the moment to drop the support for the HM10.

**Comment by DigiH** [comment]
Just out of curiosity - With @h2zero having problems with the SwitchBot Curtain decoder when testing cJSON, would you mind trying again with `progmem-decorator `but commenting out SwtichBot Curtain in `decoder.h` and `devices.h`?

Not really sure what it could be, but since it also threw an exception with cJSON …

**Comment by DigiH** [comment]
Or
`
decoder = https://github.com/theengs/decoder.git#progmen-minus-curtain`

;) ignoring the failing remaining curtain tests for now

**Comment by h2zero** [comment]
The memory use shown is an illusion with this PR, it's still allocated when loading the json's, I was just hoping ArduinoJSON would reference the flash memory instead of allocating. That was error on my part as I did not modify the code to use the `F` function and I'm not sure about it even then.

I will see if adding the required changes to the code will help. Also memory profiling for the esp32 and 8266 should be done as well as the doc size we are allocating may be excessive for these platforms, the current size is a worst case scenario value for tests mainly.

**Comment by thardie** [comment]
I did a build from progmem-decorator and it works on the nodemcuv2 with the nodemcuv2-ble. I'm able to get into the captive portal. After entering AP and MQTT info and hitting save, it crashes:

```
--------------- CUT HERE FOR EXCEPTION DECODER ---------------

Exception (28):
epc1=0x40236608 epc2=0x00000000 epc3=0x00000000 excvaddr=0x0a1c0000 depc=0x00000000

>>>stack>>>

ctx: cont
sp: 3ffff9a0 end: 3fffffc0 offset: 0190
3ffffb30:  00000000 00000000 00375f6d 00000000
3ffffb40:  3fff070c 0a1c0000 3ffffb70 4021e02f
3ffffb50:  3fff4c1c 3fff0698 3fff060c 4021e061  
3ffffb60:  3fff070c 3fff0698 3fff060c 4021565d
3ffffb70:  00000000 3fff5000 00000000 40213f54
3ffffb80:  40231dfc 00000000 000003e8 3fff350c
3ffffb90:  00000000 3ffffb9c ffffffff 00000000  
3ffffba0:  3fff3554 0a1c0000 00000000 4021e4d4
3ffffbb0:  00000000 00000000 000f000f 00000000
3ffffbc0:  3fff070c 00000001 3fff3b2c 402309c0  
3ffffbd0:  3fffd9d0 00000000 00000000 401000e9
3ffffbe0:  00000000 00000000 00000001 402115c1
3ffffbf0:  00000000 3fff3554 3fff350c 402146bc  
3ffffc00:  007a1200 00000000 00000000 69746365
3ffffc10:  00000000 00000000 00000001 401006b8
3ffffc20:  00000000 00000001 00000000 00000000
3ffffc30:  00000000 4bc6a7f0 122d0e56 00000000  
3ffffc40:  3fff070c 3fff3530 3fff350c 402168ba
3ffffc50:  3fff3fd4 3fff070c 3fff060c 4022908b
3ffffc60:  0001c9f7 00000000 3fff4bbc 00000000
3ffffc70:  3fff070c 3fff070c 3fff060c 40216af9  
3ffffc80:  3fff070c 00000001 3fff060c 40210f9f
3ffffc90:  00000000 00000000 00000001 401006b8
3ffffca0:  6e6f6365 00000000 3fff060c 00000000  
3ffffcb0:  3fff070c 00000001 3fff060c 00000000
3ffffcc0:  3fff070c 00000001 3fff060c 40216e2c
3ffffcd0:  00000000 000b000f 00000000 00000000  
3ffffce0:  73646e6f 00000000 00000000 000b000f
3ffffcf0:  00000000 3ffea33c 3fff060c 4020eed0
3ffffd00:  3ffe8c89 4029042d 00000000 3ffe95ea
3ffffd10:  3ffe8699 3fff060c 3fff060c 3ffe95ea  
3ffffd20:  3ffe8699 00000001 3fff060c 40217012
3ffffd30:  00000004 40290400 3fff0af4 40201bb0
3ffffd40:  3ffffd60 3ffffd50 0000000c 3ffe9551  
3ffffd50:  3ffe8c89 00000001 0000002c 3ffe8c89
3ffffd60:  3ffe95ea 3ffe95ea 00000005 3ffe8c89
3ffffd70:  3ffe8699 3fff060c 3fff0af4 402081cc  
3ffffd80:  40231e4c 3ffe95e5 3ffe95dd 3fff220c
3ffffd90:  0000003c 00000001 3ffe8c7c feefeffe
3ffffda0:  feefeffe feefeffe feefeffe feefeffe
3ffffdb0:  feefeffe feefeffe feefeffe feefeffe  
3ffffdc0:  feefeffe feefeffe feefeffe feefeffe
3ffffdd0:  feefeffe feefeffe feefeffe feefeffe
3ffffde0:  feefeffe feefeffe 40231e4c 3ffe95d8  
3ffffdf0:  3ffe95cc 3fff2a3c 00000800 00000001
3ffffe00:  3ffe8c7c feefeffe feefeffe feefeffe
3ffffe10:  feefeffe feefeffe 40231e4c 3ffe95c5
3ffffe20:  3ffe95c0 3fff1ba4 00000001 00000001  
3ffffe30:  3ffe9576 feefeffe feefeffe feefeffe
3ffffe40:  feefeffe 40231e4c 3ffe95ba 3ffe95b0
3ffffe50:  3fff299c 00000096 00000001 3ffe8c7c
3ffffe60:  40231e4c 3ffe9de4 3ffe95a6 3fff21c4
3ffffe70:  0000003c 00000001 3ffe8c7c 40231e4c
3ffffe80:  3ffe95a1 3ffe959c 3fff217c 0000003c
3ffffe90:  00000001 3ffe8c7c 40231e4c 3ffe9597  
3ffffea0:  3ffe9592 3fff1e04 00000006 00000001
3ffffeb0:  3ffe8c7c 40231e4c 3ffe958b 3ffe9586
3ffffec0:  3fff2134 0000003c 00000001 3ffe8c7c  
3ffffed0:  40201ec4 00000001 4023002c 40230018
3ffffee0:  00000000 00000001 3fff0ca0 4021c298
3ffffef0:  3ffe95ea 00000000 3fff1dec 40221645
3fffff00:  0001c200 0000001c 00000002 3fff0df4  
3fffff10:  0001c200 3fff0ca0 3fff0af4 402088a1
3fffff20:  feefeffe feefeffe feefeffe feefeffe
3fffff30:  feefeffe feefeffe feefeffe feefeffe  
3fffff40:  feefeffe feefeffe feefeffe feefeffe
3fffff50:  feefeffe feefeffe feefeffe feefeffe
3fffff60:  feefeffe feefeffe feefeffe feefeffe
3fffff70:  feefeffe feefeffe feefeffe feefeffe  
3fffff80:  feefeffe feefeffe feefeffe feefeffe
3fffff90:  feefeffe feefeffe feefeffe 3fff0df4
3fffffa0:  3fffdad0 00000000 3fff0de0 4021f100  
3fffffb0:  feefeffe feefeffe 3ffe8a40 4010158d
<<<stack<<<

--------------- CUT HERE FOR EXCEPTION DECODER ---------------

 ets Jan  8 2013,rst cause:2, boot mode:(3,6)

load 0x4010f000, len 3460, room 16 
tail 4
chksum 0xcc
load 0x3fff20b8, len 40, room 4
tail 4
chksum 0xc9
csum 0xc9
v0009d770
```

**Comment by thardie** [comment]
Trying it with the preconfigured MQTT and Wifi does work (associates with WiFi and connects to MQTT server)

**Comment by DigiH** [comment]
@thardie , did you actually find out if your beacons are covered by one of the Theengs Decoder decoders, and if so which one it is? 

As the minus-curtain branch doesn't really seem relevant right now I might as well briefly extend it to only include the decoder(s) relevant to your use case, for a test.

**Comment by thardie** [comment]
> @thardie , did you actually find out if your beacons are covered by one of the Theengs Decoder decoders, and if so which one it is?
> 
> As the minus-curtain branch doesn't really seem relevant right now I might as well briefly extend it to only include the decoder(s) relevant to your use case, for a test.

I didn't figure that out yet. I'll try and do that shortly, apologies.

**Comment by DigiH** [comment]
> I didn't figure that out yet. I'll try and do that shortly, apologies.

No worries, just a sample of the MQTT message you're receiving for it/them whenever you get the chance (minus the identifying MAC addresses of course)

**Comment by h2zero** [comment]
Closing this as the desired outcome is not attainable with these changes.

**Comment by DigiH** [comment]
Hi @thardie ,

I have created a reduced Decoder version, excluding all device decoders which aren't compatible with the HM10 anyway. To try out, can you change the Decoder URL in platformio.ini to

`decoder = https://github.com/DigiH/decoder#reduced-for-hm10`

The saving for `nodemcuv2-ble` with this reduced decoder is as follows

```
Decoder 0.6.2
RAM:   [==========]  95.3% (used 78056 bytes from 81920 bytes)
Flash: [======    ]  61.4% (used 641648 bytes from 1044464 bytes)
```

```
Decoder reduced-for-hm10
RAM:   [========  ]  79.9% (used 65416 bytes from 81920 bytes)
Flash: [======    ]  60.2% (used 628824 bytes from 1044464 bytes)
```

so it should be working with manual WiFi/MQTT credentials, but also with the AP setup.

Don't mind the failing tests in the branch, I just couldn't be bothered adjusting all the test cases for the deleted decoders for the time being, running fine here on an ESP32 ;)

**Pull request closed without merging**
