### PR TITLE
Jaalee JHT F525 Temperature and Humidity Sensor

### PR DESCRIPTION
**Pull request by alegsan**
Signed-off-by: Oleg Karfich <oleg.karfich@gmail.com>

## Description:
Adds support for Jaalee TH sensor. Main work is done by the [ble_monitor project](https://github.com/custom-components/ble_monitor/issues/1042). Special thanks to the guys there.

## Checklist:
  - [x] The pull request is done against the latest development branch
  - [x] Only one feature/fix was added per PR and the code change compiles without warnings
  - [x] I accept the [DCO](https://github.com/theengs/decoder/blob/development/docs/participate/development.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by DigiH** [comment]
Thanks a lot @alegsan!

Could you also please let us know if the sensor requires active scanning, or if it also broadcasts its required manufacturerdata with passive scanning, which can be set for OpenMQTTGateway
https://docs.openmqttgateway.com/use/ble.html#setting-if-the-gateway-use-active-or-passive-scanning
or Theengs Gateway
https://gateway.theengs.io/use/use.html#passive-scanning

as this information will be included in the decoders for a future update.

**Comment by DigiH** [comment]
@alegsan could you rebase your PR with the recent additions to the dev branch.

Done it ;)

**Comment by DigiH** [comment]
Merging the new decoder, thanks!

@alegsan  it still would be good to get feedback from you about the passive/active scanning requirements for this device, as otherwise it might break in the future with updates which possibly implement automatic passive/active scanning depending on device.

**Comment by alegsan** [comment]
> Merging the new decoder, thanks!

Thx for the quick merge :+1: 

> @alegsan it still would be good to get feedback from you about the passive/active scanning requirements for this device, as otherwise it might break in the future with updates which possibly implement automatic passive/active scanning depending on device.

Sorry, missed this information. Should this be mentioned somewhere in the documentation?

Checked this by disabling active scanning in OMG: no service or manufactured data anymore. So i think acitve scanning is mandatory.

**Comment by DigiH** [comment]
> Sorry, missed this information. Should this be mentioned somewhere in the documentation?

It will be once it is fully integrated, currently still a WIP ;) 

> Checked this by disabling active scanning in OMG: no service or manufactured data anymore. So i think acitve scanning is mandatory.

Thanks for the confirmation! Will include this in the decoder once the functionality has been fully implemented.

**Comment by alegsan** [comment]
Last question: how is the release cycle in this project . Would be great if OMG will use the latest changes of theengs-decoder soon ;-)

**Comment by DigiH** [comment]
It might take a bit for a new release of Decoder and then also for OMG, Gateway, App, Explorer - all the projects using the Decoder library to incorporate it into their new releases as there are other new submissions in the works for them.

You can easily use Platformio though to make your own builds and include the latest Decoder development branch by changing the line
`decoder = https://github.com/theengs/decoder.git#v1.0.0`
to
`decoder = https://github.com/theengs/decoder`

in platformio.ini, similar to how you tested your own Decoder branch.

**Comment by DigiH** [comment]
Hi @alegsan 

I have just spotted

https://github.com/custom-components/ble_monitor/issues/1285

with the changes fixed in

https://github.com/custom-components/ble_monitor/pull/1288

So I assume we should do the same fix. Do you actually have a Jaalee JHT F525 to verify any such change?

**Comment by alegsan** [comment]
> Hi @alegsan

Hi @DigiH 
 
> I have just spotted
> 
> [custom-components/ble_monitor#1285](https://github.com/custom-components/ble_monitor/issues/1285)
> 
> with the changes fixed in
> 
> [custom-components/ble_monitor#1288](https://github.com/custom-components/ble_monitor/pull/1288)
> 
> So I assume we should do the same fix. Do you actually have a Jaalee JHT F525 to verify any such change?

Thx for the hint. We already saw the apparently recently released conversation data from jaalee and already changed this for a test on our local devices. Looks good. We purchased some more devices in the end of the year and noticed that jaalee currently releases the same devices with another uuid. So we will add this also to our pull request. We will create a Pull-Request in the next days :-)

**Pull request merged**
